# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/casablanca/Release/samples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/casablanca/Release/samples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/casablanca/Release/samples/CMakeFiles /opt/casablanca/Release/samples/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/casablanca/Release/samples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named samples

# Build rule for target.
samples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 samples
.PHONY : samples

# fast build rule for target.
samples/fast:
	$(MAKE) -f CMakeFiles/samples.dir/build.make CMakeFiles/samples.dir/build
.PHONY : samples/fast

#=============================================================================
# Target rules for targets named SearchFile

# Build rule for target.
SearchFile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SearchFile
.PHONY : SearchFile

# fast build rule for target.
SearchFile/fast:
	$(MAKE) -f SearchFile/CMakeFiles/SearchFile.dir/build.make SearchFile/CMakeFiles/SearchFile.dir/build
.PHONY : SearchFile/fast

#=============================================================================
# Target rules for targets named BingRequest

# Build rule for target.
BingRequest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BingRequest
.PHONY : BingRequest

# fast build rule for target.
BingRequest/fast:
	$(MAKE) -f BingRequest/CMakeFiles/BingRequest.dir/build.make BingRequest/CMakeFiles/BingRequest.dir/build
.PHONY : BingRequest/fast

#=============================================================================
# Target rules for targets named blackjackserver

# Build rule for target.
blackjackserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackjackserver
.PHONY : blackjackserver

# fast build rule for target.
blackjackserver/fast:
	$(MAKE) -f BlackJack/BlackJack_Server/CMakeFiles/blackjackserver.dir/build.make BlackJack/BlackJack_Server/CMakeFiles/blackjackserver.dir/build
.PHONY : blackjackserver/fast

#=============================================================================
# Target rules for targets named blackjackclient

# Build rule for target.
blackjackclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackjackclient
.PHONY : blackjackclient

# fast build rule for target.
blackjackclient/fast:
	$(MAKE) -f BlackJack/BlackJack_Client/CMakeFiles/blackjackclient.dir/build.make BlackJack/BlackJack_Client/CMakeFiles/blackjackclient.dir/build
.PHONY : blackjackclient/fast

#=============================================================================
# Target rules for targets named oauth1client

# Build rule for target.
oauth1client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oauth1client
.PHONY : oauth1client

# fast build rule for target.
oauth1client/fast:
	$(MAKE) -f Oauth1Client/CMakeFiles/oauth1client.dir/build.make Oauth1Client/CMakeFiles/oauth1client.dir/build
.PHONY : oauth1client/fast

#=============================================================================
# Target rules for targets named oauth2client

# Build rule for target.
oauth2client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oauth2client
.PHONY : oauth2client

# fast build rule for target.
oauth2client/fast:
	$(MAKE) -f Oauth2Client/CMakeFiles/oauth2client.dir/build.make Oauth2Client/CMakeFiles/oauth2client.dir/build
.PHONY : oauth2client/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... samples"
	@echo "... SearchFile"
	@echo "... BingRequest"
	@echo "... blackjackserver"
	@echo "... blackjackclient"
	@echo "... oauth1client"
	@echo "... oauth2client"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

